apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: code-pipeline-i30508357 # executable id, must be unique across all your workflows (YAML files), please modify this to any value (e.g. code-pipeline-12345) if you are not the only user of your SAP AI Core instance.
  annotations:
    scenarios.ai.sap.com/description: "Tutorial to add custom code to SAP AI Core i305083"
    scenarios.ai.sap.com/name: "Code (Tutorial) i305083"
    executables.ai.sap.com/description: "Trains model on median house prices i305083"
    executables.ai.sap.com/name: "House Price (Sklearn Example) i305083"
  labels:
    scenarios.ai.sap.com/id: "learning-code-i305083"
    ai.sap.com/version: "2.0"
spec:
  imagePullSecrets:
    - name: i305083 # your docker registry secret
  entrypoint: mypipeline
  templates:
  - name: mypipeline
    steps:
    - - name: mypredictor
        template: mycodeblock1

  - name: mycodeblock1
    container:
      image: docker.io/news163/house-price:02 # Your docker image name
      command: ["/bin/sh", "-c"]
      args:
        - "python /app/src/main.py"
